[package]
name = "ironshield-types"
version = "0.1.0"
edition = "2021"
authors = [ "ebosspc <software2070@protonmail.com>" ]
description = "Shared types and utilities for the IronShield PoW system"
license = "BUSL-1.1" # Becomes Apache-2.0 after 2028-07-24

[dependencies]
# Shared dependencies accross workspaces
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
chrono.workspace = true
base64.workspace = true
wasm-bindgen.workspace = true
serde-wasm-bindgen.workspace = true

# Workspace specific dependencies
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
rand_core = { version = "0.6", features = ["getrandom"] }

[lib]
name = "ironshield_types"
path = "src/lib.rs"