[package]
name = "ironshield-types"
version = "0.1.0"
edition = "2021"
authors = [ "IronShield Developers <software@ironshield.cloud>" ]
description = "Standardized Types for IronShield Bindings"
license = "Apache-2.0"
repository = "https://github.com/IronShield-Tech/IronShield"
readme = "README.md"
keywords = ["proof-of-work", "types", "serialization", "ddos", "firewall"]
categories = ["cryptography", "web-programming", "wasm"]

[dependencies]
# Shared dependencies accross workspaces
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
chrono.workspace = true
base64.workspace = true
wasm-bindgen.workspace = true
serde-wasm-bindgen.workspace = true

# Workspace specific dependencies
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
rand_core = { version = "0.6", features = ["getrandom"] }
rand = "0.8"
web-sys = { version = "0.3", features = ["console"], optional = true }

[features]
default = []
wasm-logging = ["web-sys"]

[lib]
name = "ironshield_types"
path = "src/lib.rs"